AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  selenium-headless

  Sample SAM Template for selenium-headless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 512

Resources:
  SeleniumHeadlessFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: function/selenium-headless
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      # Architectures:
      #   - x86_64
      Layers:
        - !Ref SeleniumLayer
        - !Ref ChromeDriverLayer
  SeleniumLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: selenium Layer
      ContentUri: layer/selenium-3.141.0.zip
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7
  ChromeDriverLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: chrome driver Layer
      ContentUri: layer/headless-1.0037-chromedriver-2.37.zip
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7
